# Generated by Django 3.0.6 on 2020-06-02 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzatype', models.CharField(max_length=28, unique=True)),
                ('sm_0t', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sm_1t', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sm_2t', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sm_3t', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sm_st', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('la_0t', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('la_1t', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('la_2t', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('la_3t', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('la_st', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.BooleanField(default=False)),
                ('base_pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.BasePizza')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='orders.Order')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
        ),
    ]
