# Generated by Django 3.0.6 on 2020-06-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pizza_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='sent_to_order',
            field=models.BooleanField(default=False),
        ),
    ]
