# Generated by Django 3.0.6 on 2020-06-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pizza_sent_to_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='sent_to_order',
            new_name='sent_to_kitchen',
        ),
    ]
